Add migration guide
contember/doc pull request #20
Opened 2021-12-15 14:08 UTC by jonasNobile

2021-12-16 10:32 UTC, VojtaStanek requested changes
The migration guide looks awesome!

2021-12-16 10:32 UTC, VojtaStanek commented on docs/admin/releases/v0.8.0-alpha.7.mdx
> +* Update design using CSS custom properties by @attitude in https://github.com/contember/admin/pull/84
```suggestion

### New Features
* New design [#84](https://github.com/contember/admin/pull/84)
* Password reset support [#60](https://github.com/contember/admin/pull/60)
* One-time password support [#60](https://github.com/contember/admin/pull/60)
* Collaboration server in admin-server [#85](https://github.com/contember/admin/pull/85)
* Editor: Sortable blocks and major refactoring including new API for adding custom blocks and bug fixes [#71](https://github.com/contember/admin/pull/71), [#76](https://github.com/contember/admin/pull/76), [#82](https://github.com/contember/admin/pull/82)
* Datagrid: `HasOneSelectCell` and `HasManySelectCell` [#87](https://github.com/contember/admin/pull/87)
* Datagrid: Remembers selected filters and page when navigating back [#81](https://github.com/contember/admin/pull/81)


### Fixes
* Various select field fixes [#82](https://github.com/contember/admin/pull/82), [#83](https://github.com/contember/admin/pull/83)
* `LogoutLink` in Safari [#71](https://github.com/contember/admin/pull/71)

```

2021-12-16 10:50 UTC, attitude requested changes
Sections are new and there are some other changes required when migrating. See the comment. Besides that, I approve merging.

2021-12-16 10:50 UTC, attitude commented on docs/admin/releases/v0.8.0-alpha.7.mdx
> +Remove unnecessary component `<Box />`.  We added a new component `<Section />` which should be used instead of `<Box />` to define groups of fields.
There few things to be noted, here's my suggestion (maybe in bullets for better readability):

 "... split groups of fields on the page into logical page sections. Sections with titles are also listed within the page tabs navigation. Sections are not meant to be nested within other sections and should only be used to define top level sections of the page. Sections are required to be parent elements to dimensions not the other way around due to styling limitations."

2021-12-16 10:51 UTC, honzasladek approved these changes
Looks great! 🎉

2021-12-17 09:03 UTC, VojtaStanek approved these changes

2021-12-20 14:11 UTC, merged